# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # make vm 
    config.vm.define "vm-docker" do |node|
      node.vm.box = "centos/7"
      node.vm.provider "virtualbox" do |vb|        # Máy ảo dùng nền tảng virtualbox, với các cấu hình bổ sung thêm cho provider
        vb.name = "vm01"                           # đặt tên máy ảo tạo ra
        vb.cpus = 4                                # cấp 2 nhân CPU
        vb.memory = "4096"                         # cấu hình dùng 2GB bộ nhớ
      end           
      # node.vm.box_check_update = false
      node.vm.hostname = "vm-docker"
      node.vm.network "public_network", ip: "172.20.10.115"
      node.vm.provision "shell", path: "setup-docker.sh"   
    end
    
  end